<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseProductDao;

/**
 * The ProductDao class will maintain the persistence of Product class into the product table.
 */
class ProductDao extends BaseProductDao
{
}
